.Dd May 28, 1996
.Dt GFXCOUNT 1
.Os xs-httpd/3.5
.Sh NAME
.Nm gfxcount
.Nd The graphical digits generator for XS\-HTTPD
.Sh SYNOPSIS
.Nm http://your.site.name/cgi\-bin/gfxcount Ns Ar ?number
.Nm http://your.site.name/cgi\-bin/gfxcount Ns Ar /path/fontdir?number
.Sh DESCRIPTION
.Ql gfxcount
generates GIF images that represent a number. The number to
be generated must be supplied as an argument to the CGI
binary. An optional path may be supplied. This must be
either the name of a directory in which the files
.Pa 0.ppm
through
.Pa 9.ppm
must be located - or the prefix of a font name, in which case,
.Pa 0.ppm
through
.Pa 9.ppm
will be appended to the path specified. This way, you can
have a number of fonts in one directory.
.Pp
This program is usually not called by itself. Instead, use the
.Sy count\-*\-gfx
SSI directives supplied by the webserver. See
.Xr httpd_ssi 7
for details..
.Sh SEE ALSO
.Xr httpd 1 ,
.Xr readxs 1 ,
.Xr httpd_ssi 7
.Pp
The project homepage:
.Pa http://www.xs\-httpd.org/
