#!/bin/sh
# Copyright (C) 1995, 1996 by Sven Berkvens (sven@stack.nl)

convert() {
	sed								\
		-e 's,^ *,,'						\
		-e 's,-,\\-,g'						\
		-e 's,<HTML>,.TH '"`echo "$1" | tr '[a-z]' '[A-Z]'`"' 1 "'"`date "+%d %B %Y"`"'",'	\
		-e 's,<HEAD>,,'						\
		-e 's,<TITLE>.*</TITLE>,,'				\
		-e 's,<BODY>,,'						\
		-e 's,<H1>,.SH NAME\
,'									\
		-e 's,<H[2-9]>,.SH ,'					\
		-e 's,<UL>,,'						\
		-e 's,<OL>,,'						\
		-e 's,<DL>,,'						\
		-e 's,<DT>,.TP\
,'									\
		-e 's,<DD>,,'						\
		-e 's,<LI>,.TP\
o\
,'									\
		-e 's,<A HREF="#[^"]*">,,g'				\
		-e 's,<A HREF="\(http:[^"]*\)">,<URL: \1>,g'		\
		-e 's,<A NAME="[^"]*">,,g'				\
		-e 's,<HR>,.LP,g'					\
		-e 's,<P>,.LP,g'					\
		-e 's,&gt;,>,g'						\
		-e 's,&lt;,<,g'						\
		-e 's,<TT>,\\fB,g'					\
		-e 's,</TT>,\\fP,g'					\
		-e 's,<STRONG>,\\fB,g'					\
		-e 's,</STRONG>,\\fP,g'					\
		-e 's,<KBD>,\\fB,g'					\
		-e 's,</KBD>,\\fP,g'					\
		-e 's,<VAR>,\\fI,g'					\
		-e 's,</VAR>,\\fP,g'					\
		-e 's,<CODE>,\\fI,g'					\
		-e 's,</CODE>,\\fP,g'					\
		-e 's,<EM>,\\fI,g'					\
		-e 's,</EM>,\\fP,g'					\
		-e 's,<NOBR>,,g'					\
		-e 's,<BR>,\
.br\
,g'									\
		-e 's,</[^>]*>,,g'					\
		< "$1".html | grep -v '^$' > "$1".1
}

for i
do
	name="`basename "$i" .html`"
	convert "$name"
done
