.TH HTTPDC 1 "29 May 1996"
.SH NAME
httpdc \- Control program for the XS\-HTTPD
.SH SYNOPSIS
.ta 8n
.B httpdc
[
.I options
] command
.LP 
.SH DESCRIPTION OF HTTPDC
HTTPDC is a program that lets you control the behaviour of the XS\-HTTPD.
With this program, you can retrieve its status, kill it, restart it, etc.
.SH OPTIONS
.TP
.B \-d rootdir
Specify the root directory of the HTTPD (probably not needed).
.TP
.B \-p pidfile
Specify the pidfile to use.
.SH COMMANDS
.TP
.B ?
Gives a list of command and their meanings.
.TP
.B help
Gives a list of command and their meanings.
.TP
.B status
Display XS\-HTTPD's status. It checks whether the main daemon is running
(which reforks children if they die due to timeouts). It also checks if
the process group is running (main daemon and its children). And it display
how XS\-HTTPD was started up last time it was started.
.TP
.B kill
Kills the XS\-HTTPD. It kills only the main daemon. That daemon will kill
its children before exiting.
.TP
.B reload
This makes the XS\-HTTPD reload its database files
(\fImime.types\fP and \fIcompress.methods\fP).
.TP
.B restart
Kills the XS\-HTTPD, waits until it is completely dead and then restarts
it using the command line arguments that were used last time it was started.
If the HTTPD was not running, it will print a warning and start it anyway.
.TP
.B quit
Quits the control program.
.TP
.B exit
Quits the control program.
.LP
You may also press CTRL\-D (or any other key that means End\-Of\-Input) to
quit the program.
.SH ACKNOWLEDGEMENTS
I thank all the members at MCGV Stack who are actively involved in the
entire WWW happening.
.SH SEE ALSO
http://www.stack.nl/~sven/xs\-httpd/
.br
httpd(1), xspasswd(1), imagemap(1), clearxs(1), gfxcount(1), xsindex(1),
readxs(1)
.SH COPYRIGHT
All the programs in the XS\-HTTPD package are copyright (C) 1995, 1996
by Sven Berkvens, except the imagemapper.
.SH AUTHOR
The author of the XS WWW server and its accompanying programs is
Sven Berkvens (sven@stack.nl). I made all the programs,
except the imagemapper, which I took from the NCSA distribution,
but I cleaned it up.
