.TH HTTPD 5 "12 June 2002"
.SH FILENAME
httpd.conf \- XS httpd configuration file
.LP
.SH HTTPD.CONF LAYOUT
.LP
The httpd.conf configuration file has the following general layout:

 ... global options ...

 <System>
 ... options for main site ...
 </System>

 <Virtual>
 ... options for virtual host ...
 </Virtual>

 <Users>
 ... options for user homedirs ...
 </Users>

 <Socket>
 ... options for binding specific sockets ...
 </Socket>
.LP
Options and their values must be seperated by whitespaces.
.br
The file can have only one System and one Users section, but multiple
Virtual sections (one per virtual hostname). Keep in mind that there
are fall-back defaults for all options: you are not required to use a
configuration file and leaving out an option does not mean it will be
automatically disabled.

.LP
.SH GLOBAL OPTIONS
The following options can be set in the global section:

.TP
.B SystemRoot <directory>
The main httpd directory which contains all the data subdirectories
(like htdocs, cgi-bin, logs, ...).
.TP
.B PidFile <filename>
The file to store the current pid and the last startup command line.
This will be used by
.B httpdc(1)
for restarting and other maintainance commands.
.TP
.B UserId <username>
The username or numeric uid that will be used to process all requests.
This may not be the 'root' superuser, however 'nobody' (default) or
'http' are good candidates.
.TP
.B GroupId <groupname>
The groupname or numeric gid that will be used to process all requests.

.TP
.B ExecAsUser [true|false]
If enabled then filenames and CGI's in a user directory will be read and
executed with the permissions of that user. This is the default.
.I [cannot be disabled yet]
.TP
.B SSLCertificate <filename>
The location of the x509 certificate to be used for SSL connections.
This defaults to \fISystemRoot\fP/cert.pem
.TP
.B SSLPrivateKey <filename>
The location of the x509 certificate's key to be used for SSL connections.
This defaults to \fISystemRoot\fP/key.pem
.TP
.B UseCharset [true|false]
If enabled then character sets can be set for all files in a directory
using
.B .charset
files. The .charset file should contain one line which specifies the
character set that is used for HTML files. If this option is not set or
no .charset file can be found, the clients should assume that plain 7bit
text is used. This option is enabled by default.
.TP
.B DefaultCharset <charset>
The chacterset to be used if no user-defined charset is specified.
If this is not specified, then US-ASCII will be used.
.TP
.B UseRestrictAddr [true|false]
If enabled then .noxs files may contain one or more IP addresses - or
string prefixes of IP addresses - or IP subnets in CIDR notation. Only
clients with matching addresses will be able to retreive files from this
directory. If disabled then access to the directory will denied to
everyone if a .noxs is present and the contents of the .noxs file is
ignored. UseRestrictAddr is enabled by default.
.TP
.B UseVirtualHost [true|false]
If enabled then virtual websites can be used based on the requested
hostname; as described in
.BR httpd(1) .
This is the default. When disabled only the main (default) site can be
requested and any <Virtual> directives in the configuration file will be
ignored.
.TP
.B UseVirtualUid [true|false]
If enabled files in virtual host directories will be retreived with the
permissions of the owner over the virtual host rootdir. This can be
useful if different users maintain different sites.
.TP
.B VirtualHostDir <directory>
When virtual hosts are enabled, the server also supports "automatic"
detection of virtual hostnames - that is without specific <Virtual>
blocks in the configuration file. If the
.I VirtualHostDir
contains subdirectories with names that match a requested hostname, then
this subdirectory will be used as the HTML root directory for the
virtual host data. The \fIVirtualHostDir\fP may be an absolute path or
relative to \fISystemRoot\fP - if the setting is omited then
\fIVirtualHostDir\fP will be the same as \fISystemRoot\fP.
.TP
.B UseLocalScript [true|false]
If enabled all directories will be checked for the presence of a .xsscripts
file. This can be used to specify how files with certain
extensions should be handled by the webserver. These files use the exact
same syntax as the global script.methods file, see
.BR httpd(1)
for details.
.TP
.B UseDnsLookup [true|false]
By default the IP addresses of incoming connections are resolved through
DNS and logged with hostname information. You can disable this features
by setting UseDnsLookup to false. Note that this will also make the
environment variable REMOTE_HOST useless.
.TP
.B UsePcreRedir [true|false]
By default *.redir files contain an absolute or relative URL to redirect to,
but if this option is enabled, it make contain a path substitution as well.
This substitution must be of the form
\fBs/\fP\fIpattern\fP\fB/\fP\fIreplacement\fP\fB/\fP
Where pattern is a \fBpcrepattern(3)\fP-like regular expression that must
match the full path (without hostname). The replacement may contain grouped
backreferences indicated with \fB\\\fP\fIn\fP.
This will only work if xs-httpd is compiled with PCRE support.
.TP
.B UseLdapAuth [true|false]
By default .xspasswd contain (encrypted) passwords. If this option is
enabled, they may also contain LDAP information, in which case the webserver
will first check the LDAP database for a matching username and then the
passwords in this file. See \fBxsauth(5)\fP for more details.
This will only work if xs-httpd is compiled with LDAP support.
.TP
.B Priority
The system priority that the daemon will be running at. A lower priority causes
more favorable scheduling. The default priority is 0.
.TP
.B ScriptPriority
The CPU priority that user CGI scripts will be running at. A lower priority
causes more favorable scheduling. The default value is PRIO_MAX, which may
cause scripts to respond quite slowly, but at least your other processes won't
be suffering too much from broken scripts.
.TP
.B ScriptTimeout <minutes>
The time a CGI script is allowed to run before it will be considered runaway
and killed by the server. The time should be specified in minutes (default is 6).
Note that several browsers will kill a connection even earlier than this.
.TP
.B ScriptCpuLimit <minutes>
The amount of CPU time a CGI script is allowed to use before it will be
considered runaway and killed by the server. The time should be specified
in minutes (default is 2).

.LP
.SH SOCKET OPTIONS
It is possible to bind to multiple sockets at the same time (e.g.
http and https, or IPv4 and IPv6), using multiple <Socket> blocks
in the configuration. The following options are valid within a
Socket-block:

.TP
.B ListenAddress <hostname>
The hostname or IP-address the webserver should bind on. If the
hostname resolves to multiple IP-addresses, the webserver will only
bind to the first address resolved.
.TP
.B ListenPort <port>
The service name or port number to bind on. If you want to listen to
multiple ports, you can add more Socket-blocks.
.TP
.B ListenFamily [IPv4|IPv6]
The address family to use: IPv6 is only available when enabled at
compile-time. The default is to leave the family unspecified - which
means that your operating system can choose: in this case the httpd can
even listen to both IPv4 and IPv6 addresses. Note that most operation
systems don't allow binding to multi-family sockets, in which case you
will need to start httpds for IPv4 and IPv6 seperately.
.TP
.B Instances <number>
The number of parallell services to run.
.TP
.B UseSSL [true|false]
If enabled, use SSL instead of plain text. This can only be used if SSL
support is enabled at compile time. If this option is set then the
'https' (443) port will be used by default, instead of 'http' (80). This
option is disabled by default. Note that you may include both blocks with
and without UseSSL.

.LP
.SH SECTION OPTIONS
The following options can be set in the System, Virtual and Users sections:

.TP
.B HostName <hostname>
The hostname of the server. This is required for a Virtual section.
For the System en Users sections it defaults to the name of the machine.
.TP
.B HostAlias <hostname> [hostname ...]
One or more aliases for the previously mentioned hostname.
.TP
.B HtmlDir <directory>
The main directory containing all the HTML files. This defaults to
SystemRoot/htdocs/ for the main server and ~/.html/ for users.
It is a mandatory option in Virtual sections.
.TP
.B ExecDir <directory>
The path contain the CGI scripts. This is the directory as it is
specified in the URL, which is not necessary the same as the directory
on disk (default: cgi-bin).
.TP
.B PhExecDir <directory>
Physical CGI directory: this is the subdirectory where scripts are
stored on disk. However if you do not use the same value as ExecDir, it
is easy to get confused (default: cgi-bin)
.TP
.B LogAccess <filename>
Logfile to use for normal HTTP requests (answered with a 2xx response).
Instead of a filename, it is possible to log to an external process
using a pipe-symbol and full pathname. If the command is followed by
options or arguments, make sure to quote it using double quotes. For
example to enable logging through cronolog:
.br
LogAccess "|/usr/local/sbin/cronolog /wwwsys/logs/access_%Y%m%d"
.TP
.B LogError <filename>
Logfile or program to use for HTTP requests that trigger errors (like
file not found, 4xx responses).
.TP
.B LogReferer <filename>
Logfile or program to use for HTTP referrer information. Note that this
is only used when LogStyle traditional is selected - otherwise referrer
information will be included in the standard LogAccess file.
.TP
.B LogStyle [traditional|combined|virtual]
Defines the logfile format. Traditionally access and referrer logs will
be split over two different files (common logfile format), but using a
combined accesslog is more common nowadays (extended logfile format).
The virtual format is basically an combined log with an extra first field
indicating the virtual hostname that was accessed on the webserver.
.TP
.B IndexFiles <filename> [filename ...]
Defines the filename that should be used when the user asks for a
directory. The webserver will never autogenerate a directory index: you
can use \fBxsindex(1)\fP for that. You can specify multiple filenames
seperated by commas or whitespace. The default value is \fBindex.html,
index.htm, index.php\fP (meaning that index.htm will only be tried if
index.html is not present, etc.).
.br
If this option is omitted for the <Virtual> or <Users> section, it will
default to the definition in the <System> block. Or the previously
mentioned default if this is also unspecified.

.SH EXAMPLE
Refer to the httpd.conf.sample file that comes with the source distribution.
.SH ACKNOWLEDGEMENTS
I thank all the members at MCGV Stack who are actively involved in the
entire WWW happening.
.SH "SEE ALSO"
http://www.stack.nl/~sven/xs\-httpd/
.br
httpd(1), xspasswd(1), imagemap(1), clearxs(1), readxs(1), gfxcount(1),
xsindex(1), httpdc(1), xsauth(5), xsscripts(5)
.SH COPYRIGHT
All the programs in the XS\-HTTPD package are copyright (C) 1995-2005
by Sven Berkvens and Johan van Selst, except the imagemapper, 
.SH AUTHOR
The original author of this WWW server and its accompanying programs
is Sven Berkvens, except the imagemapper which was taken from the NCSA
distribution and cleaned up. The current maintainer is Johan van Selst.
.LP
New features have been added by other people at Stack. If you have
problems with this version please contact the Stack maintainers
(xs-httpd@stack.nl) about it and don't bother Sven.
