.TH HTTPDC 1 "29 May 1996"
.SH NAME
httpdc \- Control program for the XS\-HTTPD
.SH SYNOPSIS
.ta 8n
.B httpdc
[
.I options
] command
.LP 
.SH DESCRIPTION OF HTTPDC
HTTPDC is a program that lets you control the behaviour of the XS\-HTTPD.
With this program, you can retrieve its status, kill it, restart it, etc.
.SH OPTIONS
.TP
.B \-d rootdir
Specify the root directory of the HTTPD (probably not needed).
.TP
.B \-p pidfile
Specify the pidfile to use.
.SH COMMANDS
.TP
.B ?
Gives a list of command and their meanings.
.TP
.B help
Gives a list of command and their meanings.
.TP
.B status
Display XS\-HTTPD's status. It checks whether the main daemon is running
(which reforks children if they die due to timeouts). It also checks if
the process group is running (main daemon and its children). And it display
how XS\-HTTPD was started up last time it was started.
.TP
.B stop
Shutdown the XS\-HTTPD. It stop only the main daemon. That daemon will shut
down its children before exiting.
.TP
.B kill
Forcefully kills the XS\-HTTPD and all child processes.
.TP
.B reload
This makes the XS\-HTTPD reload its global configuration files
(\fIhttpd.conf\fP, \fImime.types\fP and \fIcompress.methods\fP).
Note that this will not set up or terminate any new sockets that have been
added to or removed from the httpd.conf - nor will it change the owner
(uid/gid) of running processes: if you want the webserver to redo its socket
configuration, you must restart it.
.TP
.B restart
Kills the XS\-HTTPD, waits until it is completely dead and then restarts
it using the command line arguments that were used last time it was started.
If the HTTPD was not running, it will print a warning and start it anyway.
.TP
.B quit
Quits the control program.
.TP
.B exit
Quits the control program.
.LP
You may also press CTRL\-D (or any other key that means End\-Of\-Input) to
quit the program.
.SH SEE ALSO
http://www.stack.nl/xs\-httpd/
.br
httpd(1), httpd.conf(5)
