.Dd March 26, 1996
.Dt IMAGEMAP 1
.Os xs-httpd/3.5
.Sh NAME
.Nm imagemap
.Nd The WWW image mapper
.Sh SYNOPSIS
.Nm http://your.site.name/cgi\-bin/imagemap/~ Ns Ar username Ns / Ns Pa mapfile
.Sh DESCRIPTION
.Ql imagemap
is a program that lets you handle imagemaps on the web. An
imagemap is basically a picture (for example a GIF file)
that has been divided into areas. A user with a browser that
understands imagemaps (most modern graphical browser do)
can then click on a certain part of the image. An
area\-specific action then occurs.
.Pp
For example, consider a GIF picture with two areas on it: a
box on the left side and a circle on the right side. Then
the user who created the pictures can define what will
happen if the remote user clicks on the box, what will
happen if the circle is pressed, and also what happens if
the user clicks on the picture, but not on the box or the
circle (the default).
.Pp
.Xr imagemap 1
is not a program that allows the user to define the map.
There are other programs that do this; for example,
.Xr mapedit 1
is a good one.
.Xr imagemap
is the program that handles the actions for the webserver.
.Pp
Note that the
.Xr imagemap 1
program runs without special privileges, which means that the
.Ar mapfile
must be accessible and world-readable on the local system.
The mapfile is never retrieved through the webserver, even
though it usually resides inside the normal webdocuments
tree.
.Sh EXAMPLES
What a user must do is create a map file (either by hand,
which is not very easy, or by using a program like mapedit).
Then, he or she must use something like the following in
his/her webpage:
.Pp
.Bd -literal -offset indent -compact
<A\ HREF="http://site/cgi\-bin/imagemap/~username/pics/image.map">
 <IMG SRC="pics/image.gif" ISMAP>
</A>
.Ed
.Pp
In other words, make a
.Sy href
anchor to the imagemapper and use an image as the contents
of the anchor. Do not forgot to specify the
.Sy ismap
keyword in the
.Sy img
tag.
.Sh SEE ALSO
.Xr httpd 1 ,
.Xr httpd_cgi 7
.Pp
The project homepage:
.Pa http://www.stack.nl/xs\-httpd/
.Sh HISTORY
This program is derived from the NCSA httpd distribution,
which can be found at
.Pa http://hoohoo.ncsa.uiuc.edu/cgi/ .
It was cleaned up and converted for inclusing in the
xs\-httpd distribution in 1995.
