.TH READXS 1 "26 March 1996"
.SH NAME
readxs \- Display the WWW counter file status
.SH SYNOPSIS
.ta 8n
.B readxs
[
.I options
] URI
.LP 
.SH DESCRIPTION OF READXS
READXS is a program that lets you read the WWW counter file.
.SH RUNNING READXS
Say you have a counter installed on your WWW page using the WWW
server's server side includes. Say this page is called \fBindex.html\fP.
Then you can get the value of this counter on standard output for use
in shell scripts using this program. In this case you could type:
.LP
readxs /~\fIUSER\fP/index.html
.SH OPTIONS
.TP
.B \-d
Display the "day" type counter.
.TP
.B \-m
Display the "month" type counter.
.TP
.B \-t
Display the "total" type counter (this is the default).
.TP
.B \-l
Display last access timestamp.
.TP
.B \-v
Display counter datafile version id (for debugging purposes).
.TP
.B \-w <number>
Set the selected type counter to the specified number.
This option may only be used by an administrator and should be used with
care as it can be used to set "impossible" values. If you want to reset
the counters, use clearxs(1) instead.

.SH SEE ALSO
http://www.stack.nl/xs\-httpd/
.br
httpd(1), clearxs(1), gfxcount(1)
