.Dd June 12, 2002
.Dt XSAUTH 5
.Os xs-httpd/3.5
.Sh NAME
.Nm \.xsauth
.Nd XS-httpd authentication data
.Sh DESCRIPTION
An
.Pa .xsauth
file informs the xs\-httpd webserver which authenticated
users should be granted read access to a
directory-hierarchy. Only users mentioned in this file can
view the available data.
.Pp
This file is created with the
.Xr xspasswd 1
utility. This can also be used to add more username and
password combinations later. However this utility can not be
used to remove users or to add special options: for this you
will need to edit the file manually and remove the line that
mentions the obsolete user entry.
.Pp
The
.Pa .xsauth
file can be used in data directories
.Pq Sy HtmlDir
as well as in cgi-bin script directories
.Pq Sy PhExecDir .
So there is no need to implement authentication support in
CGI scripts.
.Pp
If you want to disallow access through the web-interface completely, or
you want to restrict access based on IP addresses, use a
.Pa .noxs
file instead.
.Ss Password Entries
Normal password entries consist of a
.Ql L
(locked) or
.Ql U
(unlocked), indicating if the password entry may be modified
through the web-interface, using the
.Xr xschpass 1
CGI binary (which is no longer installed by default). This
letter is immediately followed by the username, a colon and
the encrypted version of the password. This is optionally
followed by an additional colon and a hash value to be used
for digest access authentication.
.Pp
On systems that don't have a standard
.Xr crypt 3
function available, all passwords will be stored unencrypted
instead.
.Ss LDAP Authentication
If LDAP support is enabled at compile time, then special
directives can be used in
.Xr xsconf 5
files to enable password checks via a remote authentication
server. The use of special LDAP directives in
.Pa .xsauth
files is deprecated and will not be supported in future versions.
.Sh SEE ALSO
.Xr httpd 1 ,
.Xr xspasswd 1 ,
.Xr xsconf 5
.Pp
The project homepage:
.Pa http://www.stack.nl/xs\-httpd/
