.Dd June 23, 2007
.Dt XSCHPASS 1
.Os xs-httpd/3.5
.Sh NAME
.Nm xschpass
.Nd Change password for access to protected web-directories
.Sh SYNOPSIS
.Nm http://your.site.name/cgi\-bin/xschpass/~ Ns Ar username Ns / Ns Pa directory
.Sh DESCRIPTION
.Ql xschpass
is a program that lets remote users change the password that
they use to access a protected web-directory with the
xs\-httpd webserver. This allows users to set a password
that is only known by themselves and not even by the person
who controls the web-directory and who set up the initial
password.
.Pp
Accounts can not be added or removed through the web-interface -
this can only be done by a person with local directory access
through
.Xr xspasswd 1 .
Also the access type (basic or digest) can only be changed with
.Xr xspasswd 1 ;
if both basic and digest authentication are enabled for a user,
then setting a new password using
.Xr xschpass 1
will update both passwords.
.Sh EXAMPLES
To change the password that is used to access the URL
.Bd -literal -offset indent -compact
.Pa http://your.site.name/~johans/protected/index.html
.Ed
one should visit the following
.Ql xschpass
location:
.Bd -literal -offset indent -compact
.Pa http://your.site.name/cgi-bin/xschpass/~johans/protected/
.Ed
.Sh SEE ALSO
.Xr httpd 1 ,
.Xr xspasswd 1 ,
.Xr httpd_cgi 7
.Pp
The project homepage:
.Pa http://www.xs\-httpd.org/
