.TH XSPASSWD 1 "26 March 1996"
.SH NAME
xspasswd \- Manager for WWW authentication passwords using the XS\-HTTPD
.SH SYNOPSIS
.ta 8n
.B xspasswd
.RI [ -l | -u ]\ [ user ]
.LP 
.SH DESCRIPTION OF XSPASSWD
XSPASSWD is a program that lets you manage the usercode/password database
for the authentication feature of the XS\-HTTPD.
.LP
Authentication works very simply: if a file called \fI.xsauth\fP is present
in the directory in which a file is going to be retrieved, then the remote
user will be asked for a usercode and password before the file is allowed
to be retrieved. This program manages the \fI.xsauth\fP file.
.SH RUNNING XSPASSWD
Change your current directory to the directory that you wish to protect
with usercodes and passwords. Note that subdirectories of that subdirectory
will also be protected.
.LP
Then, type \fBxspasswd\fP. The program will ask you for a username (unless
you already supplied this as an argument on the command line).
Type a username and press ENTER. Then, the program asks
for a password for that username. Type something press ENTER. The program
then asks you to re\-enter the password that you just typed. Do that and
press ENTER again. the program will update (or create) the \fI.xsauth\fP file.
.LP
Note that you can have as many usercodes and passwords as you wish.
.LP
You can also use this program to change passwords. Just type an existing
username when the program prompts you for a username. You do not have to
enter the old password.
.LP
The \fBxspasswd\fP accepts two mutually exclusive arguments: \fB-l\fP to
lock an account and \fB-u\fP to unlock an account. Locked accounts may
not be changed using the webinterface (see below).
By default all accounts are unlocked.
.SH THE WWW FORM
This program has a similar interface for the WWW. The webinterface is
called \fBxschpass\fP. It can be used by making a link to the following URL:
.LP
http://your.site.name/cgi\-bin/xschpass/~\fIUSERNAME\fP/\fIdirectory\fP
.LP
where \fIUSERNAME\fP is your usercode on that system. \fIdirectory\fP is
the directory in which the \fI.xsauth\fP file is situated.
.LP
It is not possible to change a password using the WWW form if the account
has been locked using the \fB-l\fP option when the password was initially
created (or updated using \fBxspasswd\fP). 
Users using the WWW form are only allowed to change a password if they
know the old password.

.SH SEE ALSO
http://www.stack.nl/xs\-httpd/
.br
httpd(1), httpd.conf(5), xsauth(5), xsconf(5)
