.Dd March 26, 1996
.Dt XSPASSWD 1
.Os xs-httpd/3.5
.Sh NAME
.Nm xspasswd
.Nd Manager for WWW authentication passwords
.Sh SYNOPSIS
.Nm xspasswd
.Op Fl b | Fl d
.Op Fl l | Fl u
.Op Fl f Ar filename
.Op Ar username
.Sh DESCRIPTION
.Ql xspasswd
is a program that lets you manage the usercode/password
database for the authentication feature of the xs\-httpd
webserver.
.Pp
Authentication works very simply: if a file called
.Pa .xsauth
is present in the directory in which a file is going to be
retrieved, then the remote user will be asked for a usercode
and password before the file is allowed to be retrieved.
This program manages the
.Pa .xsauth
file. Using the
.Fl f
flag an alternative filename can be used; however these files
are not automatically recognised by the server as authentication
files.
.Pp
The program accepts the mutually exclusive arguments
.Fl l
to lock an account and
.Fl u
to unlock an account. Locked accounts may not be changed
using the web-interface (see below). By default all accounts
are unlocked.
.Pp
The other options are also mutually exclusive:
.Fl b
to store passwords for basic authentication (the old method,
where passwords will be stored encrypted, but sent over the
wire in plain text) and
.Fl d
to store passwords for use with digest authentication (where
more sensitive information is stored on disk, but only the
checksum of user and password data is sent over the wire).
However in this case password hashes are also stored to be
able to handle basic authentication fallback in case the
client doesn't understand digest authentication.
.Pp
For optimal security it is suggested local data is never
made accessible to other users of the system and that
authentication details and sensitive content are
transferred over a secure channel (i.e. using https).
In this case digest authentication does not add
any additional security.
.Sh EXAMPLES
Change your current directory to the directory that you wish
to protect with usercodes and passwords. Note that
subdirectories of that subdirectory will also be protected.
Then, type
.Ql xspasswd .
The program will ask you for a username (unless you already
supplied this as an argument on the command line). Next, the
program asks for a password for that username.The program
will ask you to re\-enter the password after you have given
it. When you have done this, the program will update (or
create) the
.Pa .xsauth
file.
.Pp
By running the program again, you can add as many usercodes
and passwords as you wish. You can also use this program to
change passwords. Just type an existing username when the
program prompts you for a username. You do not have to enter
the old password. Be aware that the locked status and digest
hash may be lost if you don't specify
.Fl l
and
.Fl d
when changing a password, since the options default to
.Fl u
and
.Fl b .
.Sh DIAGNOSTICS
.Ex -std xspasswd
.Sh SEE ALSO
.Xr httpd 1 ,
.Xr xschpass 1 ,
.Xr xsauth 5
.Pp
The project homepage:
.Pa http://www.stack.nl/xs\-httpd/
.Sh STANDARDS
.Rs
.%R RFC 2617
.%T HTTP Authentication: Basic and Digest Access Authentication
.%D June 1999
.Re
